#!/bin/sh
# SCRIPT_VERSION="1.4.0"

trap 'rm -f "${COOKIE_FILE:-}" "${HTML_FILE:-}"' EXIT
LOG_FILE="/tmp/portal_login.log"
echo "Starting portal login sequence..." | tee -a "$LOG_FILE"

# Wait for network configuration
echo "Waiting for IP, Gateway, and DNS..." | tee -a "$LOG_FILE"
i=1
while [ $i -le 20 ]; do
    if ip route | grep -q default && nslookup neverssl.com >/dev/null 2>&1; then
        echo "Network and DNS are ready!" | tee -a "$LOG_FILE"
        sleep 2
        break
    fi
    sleep 1
    i=$((i + 1))
done

COOKIE_FILE=$(mktemp)
HTML_FILE=$(mktemp)
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

echo "Step 1: Fetching landing page via NeverSSL redirect..." | tee -a "$LOG_FILE"
EFFECTIVE_URL=$(curl -m 15 -k -L -w "%{url_effective}" -o "$HTML_FILE" -c "$COOKIE_FILE" -b "$COOKIE_FILE" -A "$USER_AGENT" "http://neverssl.com")

echo "Effective Landing URL: $EFFECTIVE_URL" | tee -a "$LOG_FILE"

if [ -z "$EFFECTIVE_URL" ] || [ "$EFFECTIVE_URL" = "http://neverssl.com" ]; then
    echo "ERROR: Failed to retrieve captive portal redirect." | tee -a "$LOG_FILE"
    exit 1
fi

# Extract BASE_URL and FORM_ACTION dynamically
BASE_URL=$(echo "$EFFECTIVE_URL" | sed -n 's/\(https*:\/\/[^\/]*\).*/\1/p')
echo "Base URL: $BASE_URL" | tee -a "$LOG_FILE"

FORM_ACTION=$(sed -n 's/.*action="\([^"]*\)".*/\1/p' "$HTML_FILE" | head -n1 | tr -d '\015')
echo "Extracted Action: $FORM_ACTION" | tee -a "$LOG_FILE"

if [ -z "$FORM_ACTION" ]; then
    echo "WARNING: Could not find form action in HTML, using default fallback /login" | tee -a "$LOG_FILE"
    FORM_ACTION="/login"
fi

# Construct the final dynamic Login URL
if [ "${FORM_ACTION#/}" != "$FORM_ACTION" ] || [ "${FORM_ACTION#http}" = "$FORM_ACTION" ]; then
    FORM_ACTION_CLEAN=$(echo "$FORM_ACTION" | sed 's/^\///')
    LOGIN_URL="${BASE_URL}/${FORM_ACTION_CLEAN}"
else
    LOGIN_URL="$FORM_ACTION"
fi
echo "Constructed Login URL: $LOGIN_URL" | tee -a "$LOG_FILE"

# Simulate standard AJAX click logs generated by clickLogs.js to replicate browser behavior
CLICK_LOGS_PATH=$(sed -n 's/.*data-click-logs="\([^"]*\)".*/\1/p' "$HTML_FILE" | head -n1 | tr -d '\015')
if [ -n "$CLICK_LOGS_PATH" ]; then
    CLICK_LOGS_URL="${BASE_URL}${CLICK_LOGS_PATH}"
    echo "Step 1.5: Simulating landing page click logs to $CLICK_LOGS_URL..." | tee -a "$LOG_FILE"
    curl -m 10 -k -A "$USER_AGENT" -b "$COOKIE_FILE" -c "$COOKIE_FILE" \
        -e "$EFFECTIVE_URL" \
        --data-urlencode "action=load" \
        --data-urlencode "itemType=landing_page" \
        --data-urlencode "itemValue=start" \
        "$CLICK_LOGS_URL" > /dev/null 2>&1

    curl -m 10 -k -A "$USER_AGENT" -b "$COOKIE_FILE" -c "$COOKIE_FILE" \
        -e "$EFFECTIVE_URL" \
        --data-urlencode "itemType=landing_page" \
        --data-urlencode "itemValue=connect" \
        --data-urlencode "itemAdditional=oneclick" \
        "$CLICK_LOGS_URL" > /dev/null 2>&1
fi

echo "Step 2: Submitting login form..." | tee -a "$LOG_FILE"
RESPONSE=$(curl -m 15 -k -L -v \
    -A "$USER_AGENT" \
    -b "$COOKIE_FILE" \
    -c "$COOKIE_FILE" \
    -e "$EFFECTIVE_URL" \
    --header "Origin: ${BASE_URL}" \
    --data-urlencode "login=oneclick" \
    -w "
HTTP_STATUS: %{http_code}
" \
    "$LOGIN_URL")

echo "Login Response Output:" | tee -a "$LOG_FILE"
echo "$RESPONSE" | tee -a "$LOG_FILE"

echo "Verifying real Internet connectivity (polling for up to 40 seconds)..."
i=1
while [ $i -le 10 ]; do
    CHECK_CODE=$(curl -k -s -o /dev/null -w "%{http_code}" -m 8 "http://connectivitycheck.gstatic.com/generate_204")
    if [ "$CHECK_CODE" = "204" ] || [ "$CHECK_CODE" = "200" ]; then
        echo "SUCCESS: Internet connection verified!"
        exit 0
    fi
    echo "Attempt $i: Not connected yet (HTTP Check Code: $CHECK_CODE). Waiting..."
    sleep 4
    i=$((i + 1))
done
echo "ERROR: Portal request completed but no Internet connectivity established after 40 seconds."
exit 1